spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: src/main/resources/static/**

server:
  port: 8080
  ssl:
    key-store: classpath:server.jks
    key-store-type: JKS
  http2:
    enabled: true